export enum ErrorMessage {
  dateInFuture = 'You need to selected date and time is in the future.',
  selectCategory = 'You need to select at least one category.',
  dateNotSelected = 'Date or time is not selected.',
  failedAdd = 'Failed to add task!',
  failedLoad = 'Failed to load tasks!',
  failedDelete = 'Failed to delete task!',
  failedDeleteSelected = 'Failed to delete selected tasks!',
  failedSetCompleted = 'Failed to set completed to selected task!',
  failedAddSelected = 'Failed to add selected task!',
  selectOneTask = 'You need to select at least one task.',
  unknownError = 'Something goes wrong...',
  notExist = 'Task with id is not exist!',
  failedUpdatePosition = 'Failed to update task position!',
}
